Fix variable enabled=false results in errors
cloudposse/terraform-aws-multi-az-subnets pull request #47
Opened 2021-04-20 16:45 UTC by paulrob-100

## what
* Fix #46
* Add local availability_zones which is empty if disabled
  * private_count and public_count are either 0 if disabled or the length of the local.availability_zones list
  * therefore aws resource counts will not reference empty list in element function
  * also guaranteed to have same number of elements in zipmap function
* Added convenience local lists of tuples for outputs
* Note az_ngw_ids is now an empty map if disabled - previously a map of constant "0"
 * dummy_az_ngw_ids is no longer referenced so remove
* Transform local lists of tuples to output maps
  * since private_count and public_count are not both >0, no ellipsis needed in transform, producing single map value
  * output maps are all empty if disabled

## why
* Users should be able to set the enabled flag to false
* This is useful when used in conjunction with the terraform-yaml-stack-config module where subnets may be disabled but yaml configuration ready to flip the flag 
 
## references
* closes #46

2021-04-25 06:26 UTC, Nuru requested changes
Thank you for this, and thank you especially for adding tests. 

We can accept this as is, but if you have the energy, I would appreciate it if you would please help bring this module up to our current standards. 

### UPDATE: I know this is asking a lot, really too much. I will take care of it for you.


Update the `label` modules and usage:
- Replace `module.this.enabled` with `local.enabled` everywhere
- Update labels to version 0.24.1
- Replace old and unhelpful

```hcl
  attributes = compact(concat(var.attributes, ["public"]))
```

with

```hcl
  attributes = ["public"]
```

(and same for "private" label)

Also please run the following commands and check in the changes:
```
make init
make github/init
make pr/auto-format
```

For extra credit, merge #41 into this PR first.

2021-04-25 06:26 UTC, Nuru commented on main.tf
> +  availability_zones = (module.this.enabled) ? var.availability_zones : []
The new style guide is 
```suggestion
  enabled = module.this.enabled
  
  public_enabled     = local.enabled && var.type == "public"
  private_enabled    = local.enabled && var.type == "private"
  availability_zones = local.enabled ? var.availability_zones : []
```

2021-04-25 06:27 UTC, Nuru commented
/test all

2021-04-26 07:26 UTC, Nuru commented
/test all

2021-04-26 07:30 UTC, Nuru approved these changes

2021-04-26 07:47 UTC, merged

2021-04-26 09:03 UTC, paulrob-100 commented
Thank you for your review and merge @Nuru. 
I also noticed the cloudposse vpc module using module.this.enabled instead of var.enabled so was going to update that. 
I can help with any remaining review comments. Let me know if I can assist please.